/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package codecheck;

public class Library {
    public boolean someLibraryMethod() {
        System.out.println("The method is called!");
        return true;
    }
}
